export enum ActionTypes {
  GET_COVID_DATA = "FETCH_COVID_DATA_BY_COUNTRY",
  GET_COVID_DATA_SUCCESS = "COVID_DATA_SUCCESS",

  GET_CHART_DATA = "FETCH_CHART_DATA",
  GET_CHART_DATA_SUCCESS = "CHART_DATA_SUCCESS",

  LOADING_FALSE = "LOADING_FALSE",
  LOADING_TRUE = "LOADING_TRUE",

  ERROR_TRUE = "ERROR_TRUE",
  ERROR_FALSE = "ERROR_FALSE",
}
