export enum ActionTypes {
  GET_COVID_DATA = "FETCH_COVID_DATA_BY_COUNTRY",
  GET_COVID_DATA_SUCCESS = "COVID_DATA_SUCCESS",

  GET_CHART_DATA = "FETCH_CHART_DATA",
  GET_CHART_DATA_SUCCESS = "CHART_DATA_SUCCESS",

  LOADING_FALSE = "LOADING_FALSE",
  LOADING_TRUE = "LOADING_TRUE",

  ERROR_TRUE = "ERROR_TRUE",
  ERROR_FALSE = "ERROR_FALSE",

  SET_COUNTRY = "SET_COUNTRY",

  SET_GLOBAL_CASES = "SET_GLOBAL_CASES",

  TOGGLE_MODAL = "TOGGLE_MODAL",

  CONTROL_CHART_PERIOD = "CONTROL_CHART_PERIOD",
}
