export enum ActionTypes {
  COVID_DATA_BY_COUNTRY = "FETCH_COVID_DATA_BY_COUNTRY",
  COVID_DATA_SUCCESS = "COVID_DATA_SUCCESS",
  COVID_DATA_ERROR = "COVID_DATA_ERROR",

  FETCH_CHART_DATA = "FETCH_CHART_DATA",
  CHART_DATA_SUCCESS = "CHART_DATA_SUCCESS",
  CHART_DATA_ERROR = "CHART_DATA_ERROR",
}
